---
- name: 'Clone latest git'
  # command: "/usr/bin/git clone {{ git }} /tmp/pulp/{{ inventory_hostname }}"
  git:
    repo: "{{ git }}"
    dest: "/tmp/pulp/{{ inventory_hostname }}"
    force: yes

- name: 'Update Code Version'
  command: "{{ inventory_dir }}/bin/update-version.py --version {{ version }}-0.1.alpha /tmp/pulp/{{ inventory_hostname }}"

- name: 'Update Spec Version'
  command: "{{ inventory_dir }}/bin/update-version.py --version {{ version }}-0.1.alpha {{ inventory_dir }}/packages/{{ inventory_hostname }}"
