---
- name: "Tito release test scratch"
  command: "tito release {{ releasers | join(' ') }} --scratch --test"
  args:
    chdir: "packages/{{ inventory_hostname }}"

- name: "Wait for tasks"
  shell: "koji list-tasks --mine --quiet"
  register: waiting_on_koji
  until: ("(no tasks)" in waiting_on_koji.stdout)
  delay: 15
  retries: 999

